---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : charlesgao
production_url : http://blog.charlesgao.com/

posts:
  permalink: 
  summary_lines: 20
  latest: 10

pages:
  permalink: 'pretty'
