title : Bottom Coder
tagline: Just another coder...
author :
  name : Charles Gao
  email : tjcharlesgao@gmail.com
  github : gaoyuan
  twitter : charlesgao
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
